apiVersion: apps/v1
kind: Deployment
metadata:
  name: verse-recommender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: verse_recommender
  template:
    metadata:
      labels:
        app: verse_recommender
    spec:
      containers:
      - name: verse-recommender
        image: bbplus3/verse-recommender:latest
        ports:
        - containerPort: 8501
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"

---
apiVersion: v1
kind: Service
metadata:
  name: verse-recommender-service
spec:
  selector:
    app: verse_recommender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
